// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
		int N = Integer.parseInt(args[0]);
		int lessOrEquel = 0;
		int moreThanHalf = 0;
		for (int i = 0; i < N; i++) {
			double randomNum = Math.random();
			if(randomNum <= 0.5){
				lessOrEquel ++;
			}else {
				moreThanHalf++;
			}
		}
		System.out.println("> 0.5:  "  + moreThanHalf + " times");
		System.out.println("<= 0.5: "  + lessOrEquel + " times");
		if(moreThanHalf ==0 || lessOrEquel==0){

		}else{
			double ratio = (double)moreThanHalf / lessOrEquel;
			System.out.println("Ratio:  " + ratio);
		}
	}




}
